/* File generated with Shader Minifier 1.1.1
 * http://www.ctrl-alt-test.fr
 */
#ifndef SHADER_CODE_H_
# define SHADER_CODE_H_
# define U_TEX0 "v"

const char fragment_glsl[] = ""
 "#version 130\n"
 "uniform sampler2D v;"
 "float z=gl_TexCoord[0].x-11,f;"
 "float m()"
 "{"
   "return fract(sin(f++)*43758.5);"
 "}"
 "vec2 i=(gl_FragCoord.xy-vec2(640,360))/640.;"
 "float y,c=1000.,g=1000.,s=1000.;"
 "float m(vec3 m)"
 "{"
   "s=m.y-(.5+.5*cos(m.x*2))*.1;"
   "float f=max(s,length(m.xz)-5.5),z=1,v=1.6;"
   "if(y<1)"
     "return f;"
   "vec3 i=normalize(vec3(-1,1.2,-1)),n=normalize(cross(i,vec3(0,1,0)));"
   "if(y>12&&y<18)"
     "g=(length(mod(m*2-1.02+y/2,2)-1)-mix(.001,.06,(y-12)/5))/2,f=min(f,g);"
   "int x=int(min(floor(y-1),7));"
   "float t=min(.3+y/6,1);"
   "m/=t;"
   "for(int l=0;f=min(f,t*max(m.y-1,max(-m.y,length(m.xz)-.1/(m.y+.7)))/z),m.xz=abs(m.xz),m.y-=1,l<x;m*=mat3(n,normalize(cross(n,i)),i),m*=v,z*=v,++l)"
     ";"
   "if(y<25)"
     "return f;"
   "return min(f,c=max(0,length(m)-.25)/z);"
 "}"
 "float x(float y)"
 "{"
   "return fract(sin(y)*43758.5);"
 "}"
 "float n(vec2 y)"
 "{"
   "return x(y.x+y.y*57.);"
 "}"
 "float r(vec2 y)"
 "{"
   "vec2 m=floor(y),z=smoothstep(0.,1,fract(y));"
   "return mix(mix(n(m+vec2(0,0)),n(m+vec2(1,0)),z.x),mix(n(m+vec2(0,1)),n(m+vec2(1,1)),z.x),z.y);"
 "}"
 "vec4 t(vec2 m)"
 "{"
   "return m.y*=1.77778,texture(v,m/2+.5)*1.05;"
 "}"
 "void main()"
 "{"
   "if(gl_TexCoord[0].w>.5)"
     "{"
       "y=max(0,z)/3.;"
       "y=n(floor(gl_FragCoord.xy))+(floor(y)+clamp(fract(y)*2,0,1));"
       "y=floor(y);"
       "float v=1.5;"
       "vec2 l=vec2(0);"
       "if(y>8&&y<12)"
         "v=y-6,l=vec2(cos(y*2),sin(y*3))/3;"
       "if(y>25&&y<29)"
         "v=5.5,l=vec2(cos(y*2),sin(y*3))/3;"
       "vec3 x=vec3(-2.5,.5+cos(y*17)*.1,3.),p=normalize(vec3(i.xy+l,v));"
       "if(y==10)"
         "x.y+=2;"
       "vec3 a=vec3(0,1.3,0),o=normalize(a-x),e=normalize(cross(o,vec3(0,1,0))),C=normalize(cross(o,-e));"
       "p=mat3(e,C,o)*p;"
       "gl_FragColor.xyz=vec3(.8,.8,1)/6;"
       "float u=20.,k=0.,d=0.;"
       "for(int F=0;F<100;++F)"
         "{"
           "d=m(x+p*k);"
           "if(d<.001)"
             "break;"
           "k+=d;"
           "if(k>10)"
             "return;"
         "}"
       "{"
         "vec3 F=x+p*k;"
         "gl_FragColor.xyz=vec3(.75,.6,.4)/1.5;"
         "if(c<.002)"
           "gl_FragColor.xyz=vec3(1,.7,.8);"
         "if(s<.02&&(y<17||y>22))"
           "gl_FragColor.xyz=vec3(.5,1,.6)/3;"
       "}"
       "vec3 F=normalize(vec3(1,3+cos(y)/2,1+sin(y*3)/2));"
       "float h=.01,b=m(x+p*k+F*h),w=max(0,(b-d)/h),T=m(x+p*k+vec3(0,1,0)*h),D=max(0,.5+.5*(T-d)/h);"
       "{"
         "vec3 q=x+p*k;"
         "if(y>12&&y<22)"
           "if(g<.01||T+b/7>.0017&&pow(r(q.xz*8),2)>abs(y-18)/5.)"
             "gl_FragColor.xyz=vec3(.65);"
       "}"
       "vec3 q=normalize(vec3(1,3+cos(y)/2,1+sin(y*3)/2));"
       "float Z=.01,Y=m(x+p*k+q*Z),X=max(0,(Y-d)/Z),W=m(x+p*k+vec3(0,1,0)*Z),V=max(0,.5+.5*(W-d)/Z);"
       "{"
         "vec3 U=x+p*k;"
         "if(y>12&&y<17)"
           "if(g<.01||W+Y/7>.0017&&r(U.xz*8)<(y-12)/3.)"
             "gl_FragColor.xyz=vec3(.65);"
       "}"
       "vec3 U=x+p*(k-.001);"
       "k=.1;"
       "float S=1.;"
       "for(int R=0;R<30;++R)"
         "{"
           "d=m(U+q*k)+.01;"
           "S=min(S,d*50+.3);"
           "if(d<.0001)"
             "break;"
           "k+=d;"
         "}"
       "gl_FragColor.xyz*=1*S*(.2+.8*X)*vec3(1,1,.9)*.7+V*vec3(.85,.85,1)*.4;"
     "}"
   "else"
     "{"
       "vec3 v=vec3(.8,.8,1)/6;"
       "vec2 x=i.xy;"
       "for(int p=0;p<2;++p)"
         "{"
           "float k=mix(1./22.,.25,1.-p)*.4;"
           "ivec2 d=ivec2(floor(x/k));"
           "for(int l=-1;l<2;++l)"
             "for(int F=-1;F<2;++F)"
               "{"
                 "vec2 q=d+vec2(l,(d.x+l&1)==1?-F:F);"
                 "f=q.x*881+q.y*927+p*1801;"
                 "for(int h=0;h<11;++h)"
                   "{"
                     "vec2 Z=(q+vec2(m(),m()))*k,o=x-Z;"
                     "vec3 U=t(Z).xyz;"
                     "float S=dot(U,vec3(1./3.)),a=mix(.25,.99,pow(m(),4))*k,e=m()*acos(-1.)*2,C=length(o);"
                     "o*=mat2(cos(e),sin(e),-sin(e),cos(e));"
                     "U=mix(U,vec3(S)*1.5,pow(m(),16));"
                     "if(m()>-floor(z*2)/2/10)"
                       "v=mix(v,U,mix(.1,.4,m())*3*pow(S,.8)*mix(.8,1,cos(o.x*1200)*.5+.5)*clamp((a-C)/mix(.001,.004,m()),0,1)),v=mix(v,U/2.,mix(.14,.3,pow(m(),16))/4*clamp(1-abs(a-C)/.002,0,1));"
                   "}"
               "}"
         "}"
       "vec2 p=vec2(.001,0),l=x+(r(x*18)-.5)*.01;"
       "float d=dot(vec3(1./3.),t(l).xyz),a=dot(vec3(1./3.),t(l+p.xy).xyz),U=dot(vec3(1./3.),t(l+p.yx*1.8).xyz);"
       "v*=vec3(mix(.1,1,1.-clamp(max(abs(U-d),abs(a-d))*4,0,.13)));"
       "v=(v-.5)*1.1+.5;"
       "v*=1.-smoothstep(91,97,z);"
       "gl_FragColor.xyz=sqrt(v*mix(.9,1,r(i.xy*400)))*1.28;"
     "}"
 "}";

#endif // SHADER_CODE_H_
